### ISSUE TITLE
Hi,in your project,i dont't find the file whose name is tools

### ISSUE THREAD

**Issue by yhr971208** [baoxinchen/siammask_e#3]
Hi,in your project,i don't find the file whose name is tools

**Comment by baoxinchen** [comment]
Hi,
Thanks for checking out the code!
You need to clone this project to your computer fist: [PySot](https://github.com/STVIR/pysot)
Then, follow the install.sh file.

**Comment by yhr971208** [comment]
> 
> 
> Hi,
> Thanks for checking out the code!
> You need to clone this project to your computer first: [PySot](https://github.com/STVIR/pysot)
> Then, follow the install.sh file.

thanks!
